version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: sisrancho
    ports:
      - "80:80"
    volumes:
      - ./dist/teste/browser:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=America/Campo_Grande
    restart: unless-stopped
